### ISSUE TITLE
resolver.txt contains blank line

### ISSUE THREAD

**Issue by bugbaba** [janmasarik/resolvers#29]
Hi Jan,

While going through your stuffs, just notice this.

The final [resolvers.txt](https://github.com/janmasarik/resolvers/blob/master/resolvers.txt) file contains a blank line which might break or cause unexpected error if its used directly with some tooling.

Adding below code after https://github.com/janmasarik/resolvers/blob/master/.github/workflows/main.yml#L22 will solve this issue.

```
sed -i '/^$/d' ../resolvers.txt
```

--
Thanks

**Comment by janmasarik** [comment]
Hey @bugbaba, you're right, thanks a lot! I've added the line and pushed it to master.

Next time feel free to directly make a PR with the fix, so'll be among the contributors. :-)
